CREATE TABLE `activity_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`activityName` varchar(200) NOT NULL,
	`activityType` enum('seasonal','factory_group','ceo_signing','special_theme','other') NOT NULL DEFAULT 'other',
	`startTime` timestamp NOT NULL,
	`endTime` timestamp NOT NULL,
	`location` varchar(500) NOT NULL,
	`targetCustomers` text NOT NULL,
	`theme` varchar(200),
	`salesTarget` int,
	`expectedOrders` int,
	`averageOrderValue` int,
	`expectedVisitors` int,
	`expectedConversionRate` int,
	`productDiscounts` text,
	`onSiteDiscounts` text,
	`additionalBenefits` text,
	`productCategories` text,
	`productDescription` text,
	`productPackages` text,
	`invitationScript` text,
	`introductionScript` text,
	`closingScript` text,
	`preparationTasks` text,
	`executionTimeline` text,
	`responsibilities` text,
	`generatedPlan` text,
	`status` enum('pending','generating','completed','failed') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `activity_plans_id` PRIMARY KEY(`id`)
);
